### ISSUE TITLE
Add recent items to NO2 dataset

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data#115]
More recent data is available for the [NO2 dataset in the VEDA EarthData Dashboard](https://www.earthdata.nasa.gov/dashboard/data-catalog/no2/explore?projection=mercator%7C%7C&basemapid=satellite&datetime=2023-09-01T00%3A00%3A00.000Z) (until end of 2023) and more is coming very soon (Jan-Mar 2024).

There may already be new files in our staging bucket or where else we store the NO2 data.

## Acceptance criteria

- [x] Latest available NO2 data has been published

**Comment by j08lue** [comment]
@ividito I take it we have been working on the event-driven ingest, but we need to fast-track the update of the NO2 dataset, please.

@freitagb said he could run the discovery / ingest, but if you can get to it today, @ividito, please indicate here.

**Comment by ividito** [comment]
`no2-monthly` and `no2-monthly-diff` have been updated with new items (up to the end of 2023), but we haven't seen new assets for 2024.

As @j08lue mentioned, we're still finishing work on event-driven ingestion, so future ingests for these collections should happen automatically.

**Comment by j08lue** [comment]
I notified EO Dashboard of the update, btw: https://github.com/eurodatacube/eodash/issues/2590

**Comment by j08lue** [comment]
I can confirm the data is up-to-date through 2023 in STAC and in the VEDA Earthdata Dashboard

* https://www.earthdata.nasa.gov/dashboard/data-catalog/no2/explore?projection=mercator%7C[…]basemapid=satellite&datetime=2023-12-01T00%3A00%3A00.000Z
* https://www.earthdata.nasa.gov/dashboard/data-catalog/no2/explore?projection=mercator%7C[…]A00.000Z&layer=no2-monthly-diff&position=0.079%7C0%7C1.31

**Comment by j08lue** [comment]
Sorry, @ividito, turns out the update also includes the yearly data product, collection `OMI_trno2-COG`, where a single file was added (for 2023).

https://radiantearth.github.io/stac-browser/#/external/staging-stac.delta-backend.com/collections/OMI_trno2-COG

Is that also already in our dev catalog and can be promoted to production?

Btw, I think it would be great to rename the yearly data collection to something more straightforward, like `no2-yearly`. I'll create a separate ticket for that.

**Comment by j08lue** [comment]
Here is the 2023 file to add to the `OMI_trno2-COG` collection `veda-data-store-staging/OMI_trno2-COG/OMI_trno2_0.10x0.10_2023_Col3_V4.tif`.

I verified that it is a valid cog and has the same format as the 2022 file.

Will you take care of the ingestion, please, @ividito?

**Comment by ividito** [comment]
This data is currently available on the dashboard: https://www.earthdata.nasa.gov/dashboard/data-catalog/no2/explore?projection=mercator%7C%7C&basemapid=satellite&datetime=2023-01-01T00%3A00%3A00.000Z&layer=OMI_trno2-COG&position=26.2948%7C0%7C1.22

**Comment by j08lue** [comment]
Awesome, thanks!

I notified the EO Dashboard team...

- https://github.com/eurodatacube/eodash/issues/2609
