### ISSUE TITLE
Veda data lifecycle documentation

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-data#117]
## Description

Data lifecycle should align with IMPACT [Data Governance Framework (DGF) ](https://github.com/NASA-IMPACT/modern-dgf)around how data is added and removed form the catalog. VEDA will need to create data lifecycle documentation or at least reference the IMPACT DGF where appropriate. 

This task will involve reviewing the [IMPACT DGF](https://github.com/NASA-IMPACT/modern-dgf) and the current level of compliance. The data lifecycle process should then be documented somewhere where it can be viewed for reference (i.e. [VEDA wiki](https://github.com/NASA-IMPACT/veda-architecture/wiki/DS)).

## PI Objective

Objective DS-5: Data Publication and Data Lifecycle Strategy NASA-IMPACT/veda-architecture#457

## Acceptance Criteria

- [x] Review of IMPACT DGF and current level of compliance
- [x] Write data lifecycle documentation in [VEDA wiki](https://github.com/NASA-IMPACT/veda-architecture/wiki/DS)

**Comment by anayeaye** [comment]
Link to some brainstorming notes about data removal considerations in this collection removal task: https://github.com/NASA-IMPACT/veda-data/issues/116

**Comment by smohiudd** [comment]
Forked data governance framework for VEDA: https://github.com/NASA-IMPACT/veda-dgf
