### ISSUE TITLE
Add proper title and description to VEDA STAC

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data#123]
![image](https://github.com/NASA-IMPACT/veda-data/assets/3404817/e8d08e77-06fa-4a8a-bb48-df51a2e7a632)

## Acceptance criteria

- [x] Defined title and description
- [x] Added them to VEDA STAC

**Comment by smohiudd** [comment]
This was addressed in PR https://github.com/NASA-IMPACT/veda-backend/pull/379
