### ISSUE TITLE
Publish STAC metadata for CMR collections to VEDA STAC DB + API (titiler-cmr)

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data#127]
Publish the following metadata to the VEDA STAC API:
- https://github.com/developmentseed/stac-explorer/blob/main/public/stac/GPM_3IMERGDF.stac.json
- https://github.com/developmentseed/stac-explorer/blob/main/public/stac/MUR-JPL-L4-GLOB-v4_1.stac.json

Note: a notebook for how the metadata was completed is available here: https://github.com/developmentseed/stac-explorer/blob/main/notebooks/create-stac-for-cmr-collections.ipynb

Once completed, additions to veda-config and modifications to veda-ui will be made to support visualizing these datasets via titiler-cmr.

**Comment by ividito** [comment]
@abarciauskas-bgse These collections are available in our staging catalog:
- https://staging-stac.delta-backend.com/collections/GPM_3IMERGDF
- https://staging-stac.delta-backend.com/collections/MUR-JPL-L4-GLOB-v4_1

Let me know if there are any changes that need to be made.

**Comment by abarciauskas-bgse** [comment]
@ividito so far these look good to me - thank you!

**Comment by abarciauskas-bgse** [comment]
@ividito Once I started to integrate the GPM IMERG dataset I noted a few things which are my oversight so I apologize for not catching this sooner.

* title field was null
* id should have a version suffix (.07) to differentiate it from the previous version 06 which I think is still commonly referenced
* change the colormap for renders precipitation object from cfastie to jet (which looks more similar to what GES DISC uses on their dataset page https://disc.gsfc.nasa.gov/datasets/GPM_3IMERGDF_06/summary/)

These changes are captured in an updated version of the STAC file here: https://raw.githubusercontent.com/developmentseed/stac-explorer/main/public/stac/GPM_3IMERGDF.stac.json

We should also add dashboard:time_density: day and dashboard:is_periodic: true.

I'll take a look at MUR dataset as well and make another comment if I need changes for that dataset.
