### ISSUE TITLE
OMI metadata inconsistency - missing datetime

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data#14]
We received a "metadata bug" report from the EO Dashboard team:

> There are issues with following collection (OMI_trno2-COG).
> It seems only the last entry for 2022 has a `datetime` property, all other entries have only `start_datetime` and `end_datetime`. In principle i can adapt to this in code, but as far as i can interpret the stac standard the datetime property is required (although it can be null).
> 
> Am i missing something? It also seems strange to mix the different approaches. Just wanting to make sure i don't implement something that is not really needed.
> 
> Example request:
> [https://staging-stac.delta-backend.com/search?datetime=1970-01-01T00:00:00Z/3000-01-01T00:00[…]box=-180.0,-90.0,180.0,90.0&collections=OMI_trno2-COG](https://staging-stac.delta-backend.com/search?datetime=1970-01-01T00:00:00Z/3000-01-01T00:00:00Z&limit=100&page=1&bbox=-180.0,-90.0,180.0,90.0&collections=OMI_trno2-COG)

## Acceptance criteria

 - [x] OMI metadata is nice and consistent in `staging` STAC
 - [x] Notified the EO Dashboard team

**Comment by anayeaye** [comment]
I think we should investigate how to use the api to smooth our responses but in this exact case there is one record out of a collection of 18 items that was created with inconsistent metadata and I think the appropriate fix is to correct that one record. 
```
curl -X 'GET' \
  'https://staging-stac.delta-backend.com/search?collections=OMI_trno2-COG&limit=50' \
  -H 'accept: application/json' | jq .context                                 
  
--

{
  "limit": 50,
  "matched": 18,
  "returned": 18
}
```
```
curl -X 'GET' \
  'https://staging-stac.delta-backend.com/search?collections=OMI_trno2-COG&limit=50' \
  -H 'accept: application/json' | jq -r '.features[].properties.datetime'
 
--

2022-01-01T00:00:00+00:00
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
```

After that I think there are some standards we should think about--what do we enforce and what do we anticipate being inconsistent (all items in a collection should have the same metadata format? or should we be okay with different properties on different items within the same collection?)

**Comment by ividito** [comment]
The metadata has been corrected in `staging`, but we're still considering options to return `datetime: null` to align with the STAC spec. 

```
curl -X 'GET'   'https://staging-stac.delta-backend.com/search?collections=OMI_trno2-COG&limit=50'   -H 'accept: application/json' | jq -r '.features[].properties.datetime // empty'
```

The linked PR has more information about a possible workaround, as well as some details on the underlying issue in `pgstac`
