### ISSUE TITLE
Data Promotion to Production Strategy

### ISSUE THREAD

**Issue by ividito** [NASA-IMPACT/veda-data#146]
## Description

Promotion of datasets between staging and production will require an automated solution. The promotion strategy should address the following:

- how to transfer assets (or not) between staging and production buckets
- what approvals are needed before a dataset can be promoted to production?

~~NOTE: There are a handful of new items that need to be promoted currently from staging. This includes new NO2 data #89 and new GEOGLAM data #140~~ Moved to https://github.com/NASA-IMPACT/veda-data/issues/155

## PI Objective

Objective DS-5: Data Publication and Data Lifecycle Strategy NASA-IMPACT/veda-architecture#457

## Success Criteria

- [x] Strategy devised for promoting staged data to production
- [x] Clear documentation is provided for how a data contributed can initiate the process to promote staged data to production (how this would happen today)
- [x] Automation design issue generated (current airflow and workflows api do not fully support an automated solution, a design epic will lay out tasks to deliver a hands off process)

**Comment by smohiudd** [comment]
July 3 Discussion Notes: https://docs.google.com/document/d/1w7NG1pVB-d_3agG4kIb9qhdq2xVuFdxDO9Rz8NbeCTI/edit#heading=h.p6pytmfim4kl

**Comment by anayeaye** [comment]
Work in progress in both veda-docs and veda-data (circular references and all)

https://github.com/NASA-IMPACT/veda-data/pull/162

https://github.com/NASA-IMPACT/veda-docs/pull/161

**Comment by anayeaye** [comment]
Automation design issue: https://github.com/NASA-IMPACT/veda-data/issues/161
