### ISSUE TITLE
Automate Geoglam & NO2 dataset ingestion

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-data#155]
## Description

NO2 (#89) and Geoglam (#167, #173) datasets requires monthly ingestion as new assets are created. This is currently a manual process however should be automated. `veda-data-airflow` has a feature that allows scheduled ingestion by creating dataset specific DAGs. The file must still be transferred to the collection s3 bucket. A json file must be uploaded to the airflow event bucket. Here is an example json:

```json
{
    "collection": "emit-ch4plume-v1",
    "bucket": "lp-prod-protected",
    "prefix": "EMITL2BCH4PLM.001/",
    "filename_regex": ".*.tif$",
    "schedule": "00 05 * * *",
    "assets": {
        "ch4-plume-emissions": {
            "title": "EMIT Methane Point Source Plume Complexes",
            "description": "Methane plume complexes from point source emitters.",
            "regex": ".*.tif$"
        }
    }
}
```

## Acceptance Criteria

- [x] transfer `no2-monthly` and `no2-monthly-diff` from `s3://covid-eo-data` bucket to  `s3://veda-data-store-staging` and `s3://veda-data-store` using MWAA transfer dag
- [x] scheduled ingestion (bi weekly) json files are created and uploaded for NO2 (`no2-monthly, no2-monthly-diff`) in mwaa event bucket for staging (UAH) and production (MCP)
- [x] scheduled ingestion (bi weekly) json files are created and uploaded for  Geoglam (`geoglam`) in mwaa event bucket for staging (UAH) and production (MCP)
- [x] Validate that new ingestions are initiated in staging and production. Add new geoglam files from #167, #173 into veda-data-store-staging bucket.
- [ ] transfer, automated ingestion json configs are in veda-data

**Comment by slesaad** [comment]
Putting the discovery-items config within s3://<[EVENT_BUCKET](https://github.com/NASA-IMPACT/veda-data-airflow/blob/ff77a4409f392be1b591363f4b758f2a5e87b105/dags/generate_dags.py#L19-L20)>/collections/ in the following format: https://github.com/US-GHG-Center/ghgc-data/blob/add/lpdaac-dataset-scheduled-config/ingestion-data/discovery-items/scheduled/emit-ch4plume-v1-items.json will trigger the discovery and subsequent ingestion of the collection items based on the schedule attribute

**Comment by smohiudd** [comment]
mcp-prod will need a new release of airflow to include automated ingestion

**Comment by smohiudd** [comment]
`aws s3 ls s3://covid-eo-data/OMNO2d_HRMDifference/`

![Image](https://github.com/user-attachments/assets/84076b44-aa51-45e2-8859-63c8e3d054af)

**Comment by sandrahoang686** [comment]
Update: We have decided to run these weekly instead of bi-weekly

**Comment by anayeaye** [comment]
I added the scheduled collection configs from veda-data #177 to mcp-test and mcp-production
![Image](https://github.com/user-attachments/assets/85e14727-f383-478a-a4f5-87847bb8fbae)

**Comment by anayeaye** [comment]
It looks like the uah-staging DAG has run for geoglam and discovered no files (expected). And the DAGs for the NO2 collections are visible but have not run (I need to revisit the configs to see if this is also expected). In mcp-prod the DAGs are present but have not yet run.

**Question:** Do we expect the scheduled ingest setup for SM2A to be the same as it was for MWAA?
2 files
 
![Image](https://github.com/user-attachments/assets/8714ac9e-87f2-4195-9534-fe357c752f1e)
![Image](https://github.com/user-attachments/assets/56c2b6d6-0bef-4673-93e4-a12dd25b19c5)

**Comment by anayeaye** [comment]
UPDATE: Let's keep this open until I get a chance to add the config to the SM2A /collections bucket because we will be deprecating MWAA

**Comment by anayeaye** [comment]
Configs now in SM2A. We may later update the scheduled job regex to be more restrictive to address a recurring filename pattern change for the geoglam collection https://github.com/NASA-IMPACT/veda-data/issues/213
