### ISSUE TITLE
Convert to FLDAS to cog for June 2023 - 2024

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-data#159]
# Description
Pull the most recent [FLDAS data](https://hydro1.gesdisc.eosdis.nasa.gov/data/FLDAS/FLDAS_NOAH01_C_GL_MA.001/) from GES DISC, convert the data to COGs, and upload to the s3://veda-data-store-staging/fldas-soil-moisture-anomalies/ bucket path with the following file naming convention `FLDAS_NOAH01_SoilMoi00_10cm_tavg_C_GL_MA_ANOMyyymmm_yyyymmdd.tif` ? We need the data from June 2023 - June 2024.

**Comment by SwordSaintLancelot** [comment]
@slesaad Please close this ticket when you check the data in production.
