### ISSUE TITLE
Auto staging publish workflow

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-data#161]
# Description
Based on the data promotion to production strategy [here](https://docs.google.com/document/d/1w7NG1pVB-d_3agG4kIb9qhdq2xVuFdxDO9Rz8NbeCTI/edit#heading=h.p6pytmfim4kl), an automated workflow is to be developed which does the following on PR to veda-data:
1. publishes the data to staging
2. creates a PR in veda-config with minimal dataset config

**Comment by slesaad** [comment]
https://github.com/NASA-IMPACT/veda-data/pull/165

**Comment by smohiudd** [comment]
Discussion: carve out STAC api meta data publishing part of actions

**Comment by smohiudd** [comment]
Will get feedback on this workflow from this new ticket: https://github.com/NASA-IMPACT/veda-architecture/issues/495
