### ISSUE TITLE
Promote oco2-geos-l3-daily to production

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-data#163]
## What
The `oco2-geos-l3-daily` collection from staging (with config already in this repo) needs to be promoted to production to support the veda-docs/notebooks/quickstarts/visualize-zarr.ipynb 

## AC
- [x] `oco2-geos-l3-daily` promoted to prod

**Comment by smohiudd** [comment]
The assets for this collection are located at `s3://veda-data-store-staging/EIS/zarr/OCO2_GEOS_L3CO2_day.zarr` but `OCO2_GEOS_L3CO2_day.zarr` is actually a directory not a file so the transfer DAG failed on this transfer.

```
(notebook) jovyan@jupyter-smohiudd:~$ aws s3 ls s3://veda-data-store-staging/EIS/zarr/OCO2_GEOS_L3CO2_day.zarr/
                           PRE XCO2/
                           PRE XCO2PREC/
                           PRE lat/
                           PRE lon/
                           PRE time/
2022-08-31 21:14:56       1153 .zattrs
2022-08-31 21:14:56         24 .zgroup
2022-08-31 21:14:56       5466 .zmetadata
```
@anayeaye can you manually transfer this OCO2_GEOS_L3CO2_day.zarr directory to `veda-data-store` or should we continue to point to staging even in the production catalog?

**Comment by anayeaye** [comment]
I see what you mean. I am going to attempt a recursive copy of the contents of `s3://veda-data-store-staging/EIS/zarr/OCO2_GEOS_L3CO2_day.zarr` to `s3://veda-data-store/oco2-geos-l3-daily` with the same file structure. I also am starting to think we could just keep the notebook pointing at staging for some of this more experimental work.

**Comment by anayeaye** [comment]
```
aws s3 cp s3://veda-data-store-staging/EIS/zarr/OCO2_GEOS_L3CO2_day.zarr/ s3://veda-data-store/oco2-geos-l3-daily/ --recursive --dryrun
```
After
```
alexandrakirk@Alexandras-MacBook-Pro ~ % aws s3 ls s3://veda-data-store/oco2-geos-l3-daily/
                           PRE XCO2/
                           PRE XCO2PREC/
                           PRE lat/
                           PRE lon/
                           PRE time/
2024-08-15 18:16:04       1153 .zattrs
2024-08-15 18:16:04         24 .zgroup
2024-08-15 18:16:04       5466 .zmetadata
```

HOWEVER now that I've copied this I am wondering if that top level prefix `OCO2_GEOS_L3CO2_day.zarr` is actually part of the data structure and I should have copied to
`veda-data-store/oco2-geos-l3-daily/OCO2_GEOS_L3CO2_day.zarr` where the prefix is the collection name and then the first prefix under the collection name is OCO2_GEOS_L3CO2_day.zarr. @abarciauskas-bgse is `OCO2_GEOS_L3CO2_day.zarr` actually a part of the zarr asset or is it just EIS's bucket prefix choice?

**Comment by anayeaye** [comment]
@smohiudd I fixed this by deleting the files I had copied over yesterday and then running 
```
aws s3 cp s3://veda-data-store-staging/EIS/zarr/OCO2_GEOS_L3CO2_day.zarr/ s3://veda-data-store/oco2-geos-l3-daily/OCO2_GEOS_L3CO2_day.zarr/ --recursive --dryrun
```

```
alexandrakirk@Alexandras-MacBook-Pro ~ % aws s3 ls s3://veda-data-store/oco2-geos-l3-daily/OCO2_GEOS_L3CO2_day.zarr/
                           PRE XCO2/
                           PRE XCO2PREC/
                           PRE lat/
                           PRE lon/
                           PRE time/
2024-08-16 09:31:26       1153 .zattrs
2024-08-16 09:31:26         24 .zgroup
2024-08-16 09:31:26       5466 .zmetadata
```

**Comment by smohiudd** [comment]
Thank you!
