### ISSUE TITLE
Update permissions on this repo

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data#17]
This repo has different permissions than e.g. [veda-data-pipelines](https://github.com/NASA-IMPACT/veda-data-pipelines). Can we please apply the same, so the usual teams have adequate access?

<img width="823" alt="image" src="https://github.com/NASA-IMPACT/veda-data/assets/3404817/8dcc6324-f77e-4056-a4c3-267451d14626">

**Comment by slesaad** [comment]
Done!
