### ISSUE TITLE
Promote DOW-related collections to production

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-data#187]
## What
11 STAC Collections in staging are ready to promote to production. This ticket is to capture the work required for all collections but it may end up making sense to use this as a small epic and make a ticket for each of these collections:

```
tornadoes-2024-polygons
tornadoes-2024-paths
ps-portage-tornadoes-2024
ps-barnsdall-tornadoes-2024
ps-greenfield-pre-tornadoes-2024
ps-greenfield-post-tornadoes-2024
ps-lakeview-winchester-tornadoes-2024
ps-tornadoes-2024-difference
greenville-nightlights-tornadoes-2024
lakeview-nightlights-tornadoes-2024
tornadoes-2024-dow-vmax-greenfield
tornadoes-2024-dow-refl-greenfield
tornadoes-2024-dow-vg-greenfield
tornadoes-2024-dow-rhohv-greenfield
tornadoes-2024-dow-sw-greenfield
tornadoes-2024-dow-zdr-greenfield
tornadoes-2024-dow-refl-harlan
tornadoes-2024-dow-v-harlan
tornadoes-2024-dow-rhohv-harlan
tornadoes-2024-dow-sw-harlan
tornadoes-2024-dow-zdr-harlan
```

### Thumbnail
This thumbnail has already been uploaded, only metadata config is needed
```
    "assets": {
        "thumbnail": {
            "title": "Thumbnail",
            "description": "Photo by [ AUTHOR OR ORGANIZATION NAME ]( LINK TO AUTHOR OR ORG ) ( ALT TEXT DESCRIPTION )",
            "href": "https://thumbnails.openveda.cloud/dow-background-compressed.jpg",
            "type": "image/jpeg",
            "roles": ["thumbnail"]
        }
    }
```

### Renders
Example renders object. The renders config should be specific to each collection
```
    "renders": {
        "dashboard": {
            "bidx": [1],
            "title": "VEDA Dashboard Render Parameters",
            "assets": [
            "cog_default"
            ],
            "unscale": False,
            "colormap": {
                "1": [120, 120, 120],
                "2": [130, 65, 0],
                "3": [66, 207, 56],
                "4": [245, 239, 0],
                "5": [241, 89, 32],
                "6": [168, 0, 0],
                "7": [0, 143, 201]
            },
            "max_size": 1024,
            "resampling": "nearest",
            "return_mask": True
        }
    }
```

## Actions
- [x] Update thumbnail configuration with author, link, description
- [x] Add thumbnail asset to every dataset config
- [x] Confirm dataset configs have providers info
- [x] Confirm dataset configs have stac version and extensions
- [x] Nice to have: confirm dataset configs have renders
- [x] Nice to have: confirm dataset configs have item assets descriptions

## AC
- [x] tornadoes-2024-polygons published to production https://github.com/NASA-IMPACT/veda-data/pull/175
- [x] tornadoes-2024-paths published to production https://github.com/NASA-IMPACT/veda-data/pull/175
- [x] ps-portage-tornadoes-2024 published to production https://github.com/NASA-IMPACT/veda-data/pull/209
- [x] ps-barnsdall-tornadoes-2024 published to production https://github.com/NASA-IMPACT/veda-data/pull/208
- [x] ps-greenfield-pre-tornadoes-2024 published to production https://github.com/NASA-IMPACT/veda-data/pull/207
- [x] ps-greenfield-post-tornadoes-2024 published to production https://github.com/NASA-IMPACT/veda-data/pull/204
- [x] ps-lakeview-winchester-tornadoes-2024 published to production https://github.com/NASA-IMPACT/veda-data/pull/206
- [x] ps-tornadoes-2024-difference published to production https://github.com/NASA-IMPACT/veda-data/pull/203
- [x] greenville-nightlights-tornadoes-2024 published to production https://github.com/NASA-IMPACT/veda-data/pull/201
- [x] lakeview-nightlights-tornadoes-2024 published to production https://github.com/NASA-IMPACT/veda-data/pull/202
- [x] tornadoes-2024-dow-vmax-greenfield published to production https://github.com/NASA-IMPACT/veda-data/pull/189
- [x] tornadoes-2024-dow-refl-greenfield published to production https://github.com/NASA-IMPACT/veda-data/pull/191
- [x] tornadoes-2024-dow-vg-greenfield published to production https://github.com/NASA-IMPACT/veda-data/pull/192
- [x] tornadoes-2024-dow-rhohv-greenfield published to production https://github.com/NASA-IMPACT/veda-data/pull/193
- [x] tornadoes-2024-dow-sw-greenfield published to production https://github.com/NASA-IMPACT/veda-data/pull/194
- [x] tornadoes-2024-dow-zdr-greenfield published to production https://github.com/NASA-IMPACT/veda-data/pull/195
- [x] tornadoes-2024-dow-refl-harlan published to production https://github.com/NASA-IMPACT/veda-data/pull/196
- [x] tornadoes-2024-dow-v-harlan published to production https://github.com/NASA-IMPACT/veda-data/pull/197
- [x] tornadoes-2024-dow-rhohv-harlan published to production https://github.com/NASA-IMPACT/veda-data/pull/198
- [x] tornadoes-2024-dow-sw-harlan published to production https://github.com/NASA-IMPACT/veda-data/pull/199
- [x] tornadoes-2024-dow-zdr-harlan published to production https://github.com/NASA-IMPACT/veda-data/pull/200

**Comment by acblackford** [comment]
Json structures for all collections (the Planet doc may not have all individual structures, but nightlights and DOW should):

[dow_2024tors_dataset_description.docx](https://github.com/user-attachments/files/17850936/dow_2024tors_dataset_description.docx)
[nightlights_2024tors_dataset_description.docx](https://github.com/user-attachments/files/17850937/nightlights_2024tors_dataset_description.docx)
[planet_2024tors_dataset_description.docx](https://github.com/user-attachments/files/17850954/planet_2024tors_dataset_description.docx)

**Comment by acblackford** [comment]
tornado paths and polygons jsons are here: https://github.com/NASA-IMPACT/veda-data/pull/175/files

**Comment by acblackford** [comment]
The DOW thumbnail should be applied to only DOW-related collections. The tornado image from a storm chaser can be left for the planet, nightlights, and tracks/polygons collections.

**Comment by anayeaye** [comment]
Related veda-config pr to sort out collection ids and other parameters https://github.com/NASA-IMPACT/veda-config/pull/420/files

**Comment by smohiudd** [comment]
https://docs.google.com/spreadsheets/d/1ikHEXbW42yTCbg2XBEMenI01KhLIJrKHS8sU1UqGoFs/edit?gid=0#gid=0

**Comment by anayeaye** [comment]
These collections are all now in production and the blocked veda-config PR was merged. There are still quite a few un-reviewed PRs and a few incomplete PRs to complete in veda-data though.
