### ISSUE TITLE
Specify providers for all data collections in VEDA STAC

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data#22]
## Description

Currently, we do not have any provider information included with the collections in VEDA. We need to complete that information to be able to document **data provenance**.

To gather this information easily with multiple contributors, let us fill out this [spread sheet](https://docs.google.com/spreadsheets/d/1hF74CLrVktNVKfNg9W14uNXcgT2OvzX5q1GEgtru9Ig).

### Instructions

The [data collection spread sheet](https://docs.google.com/spreadsheets/d/1hF74CLrVktNVKfNg9W14uNXcgT2OvzX5q1GEgtru9Ig) has two sheets: The first one listing all the collections existing in [VEDA STAC](http://veda-staging-stac-browser.s3-website-us-west-2.amazonaws.com/) at the time of writing and the second one for the providers.

A collection can have multiple providers and providers can have multiple roles (`producer`, `processor`, `licensor`, `host`). In particular, please make sure to indicate `processor` correctly - if the data was transformed to load it into VEDA, this should be noted.

#### Step 1: Define new providers

Use a unique ID for each provider. Providers can be re-used and combined for each collection - e.g. both VEDA and NASA can be processors of the same collection. There is only one host, though, which will most often be VEDA (`veda-hosted`)

![image](https://user-images.githubusercontent.com/3404817/235640809-86ac20f1-e087-487f-b4ba-6bb44a0bbeaa.png)

#### Step 2: List the providers for the collection

Enter the unique IDs of the providers, separated by comma

![image](https://user-images.githubusercontent.com/3404817/235645993-a6d7b8a0-769b-4722-bbc8-279dfe964147.png)

#### Step 3: Review / approval

If you have the necessary authority / knowledge to approve that a record is correct, please tick the "approved" box.

## Acceptance criteria

- [x] Providers are specified for all collections currently in VEDA STAC in the [spread sheet ](https://docs.google.com/spreadsheets/d/1hF74CLrVktNVKfNg9W14uNXcgT2OvzX5q1GEgtru9Ig)
- [ ] #39

## Dependencies

We may need to specify some of this information both in STAC and in the Dataset configurations for the Dashboard. The first and authoritative place should be the STAC.

When this is complete, we can move on with surfacing this information several places (https://github.com/NASA-IMPACT/veda-architecture/issues/303).

This is related to the Data Governance Plan https://github.com/NASA-IMPACT/veda-architecture/issues/232

## PI Objective

https://github.com/NASA-IMPACT/veda-architecture/issues/307

**Comment by kathrynberger** [comment]
A few clarifying follow up questions:
* More specifically, clarifying what is meant by `provider`. In some cases this is very clear (e.g., `CMIP` datasets), in others it is less so. For example, with the `Caldor Fire Behavior` the underlying data used to develop this dataset is from the USGS BAER program, but they ([USGS BAER](https://burnseverity.cr.usgs.gov/baer/)) were not the ones doing the analysis that produced the dataset currently on the VEDA platform. Do I provide USGS BAER as the `producer` but not the  `processor` in the above example? 
* Similarly, using the same example above, who would be the `licensor`? How does one identify that information?

cc' @ividito @anayeaye

**Comment by j08lue** [comment]
The [STAC spec](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#provider-object) has some explanation of the roles:

> roles: The provider's role(s) can be one or more of the following elements:
> 
> **licensor**: The organization that is licensing the dataset under the license specified in the Collection's license field.
> **producer**: The producer of the data is the provider that initially captured and processed the source data, e.g. ESA for Sentinel-2 data.
> **processor**: A processor is any provider who processed data to a derived product.
> **host**: The host is the actual provider offering the data on their storage. There should be no more than one host, specified as last element of the list.

But it does not explain what the limits of "processing" are.

In my world, "processing" means changing storage/data format and perhaps reprojecting (including interpolation), maybe even converting between different units by scaling with natural constants etc. But if the meaning of the data changes substantially (new physical quantity, some model applied), the result is a new dataset and the "processor" is also the "producer".

I wonder whether any canonical definitions exist - I am sure NASA has design docs somewhere... 🤔

**Comment by kathrynberger** [comment]
Thanks @j08lue for the added insight and clarity here. I appreciate it. 
So in the example above using `Caldor Fire Behavior` the underlying dataset comes from USGS BAER so I would have considered them the underlying `producer` of the dataset itself. So you consider that not the case? 
I'll have to dig a bit deeper and understand who did the actual application/extraction of this BAER dataset for this particular AOI (i.e., VEDA? )- in which case then `VEDA` would be the `producer` and `processor`?

**Comment by j08lue** [comment]
> So in the example above using `Caldor Fire Behavior` the underlying dataset comes from USGS BAER so I would have considered them the underlying `producer` of the dataset itself.

Right, if all that was done to the data was some ETL, I would also keep the original producer and just list VEDA or EIS (slightly more specific) as processor.

**Comment by j08lue** [comment]
Right. A dataset can have several **providers**, each with their own (even overlapping) sets of roles.

My idea was that you just create all the provider/role combinations as separate lines in the "[Providers](https://docs.google.com/spreadsheets/d/1hF74CLrVktNVKfNg9W14uNXcgT2OvzX5q1GEgtru9Ig/edit#gid=101778724)" table and then reference all of those that apply, comma-separated, on the dataset row.

You can also create specific providers just for one dataset, like I did for `nasa-landsat` and `usgs-landsat` - you do not need to reuse existing ones, if it does not make things easier.

**Comment by j08lue** [comment]
Ah, right, no, we do not have a line for VEDA or EIS as processor. Please feel free to create any new lines in the Providers table you need.

**Comment by kathrynberger** [comment]
OK, thanks. That helps clarify things. So it's not just the "providor" that we are focusing on, but all the organizations that may "own" a component of it (i.e., "processor, etc"

**Comment by jsignell** [comment]
@mccabete

**Comment by jsignell** [comment]
Sorry for the harsh ping Tess, Saadiq and I were trying to figure out why you weren't showing up in list of people to @

**Comment by mccabete** [comment]
Hey @smohiudd, yes. just listed the processor as "EIS Fire" in the document directly. I will double check that with the rest of the team today.

**Comment by kathrynberger** [comment]
A comment on the status of this ticket: 
* I have been able to add `providers` and their associated roles for a good majority of the datasets in the spreadsheet. 
* There are, however, still a handful that need more specific provider information beyond a more generic `veda-processed` (e.g., any of the `LIS` related datasets, and `blue tarp` datasets) - which will require further imput/decisions to be made by the NASA team. 
* I'll pause efforts on this ticket but it is up-to-date as of the 30th of August

cc' @j08lue

**Comment by mccabete** [comment]
@smohiudd can you change producer from "EIS Fire" to "NASA EIS Fire"?
