### ISSUE TITLE
New Dataset: MODIS Tri-Annual Differences

### ISSUE THREAD

**Issue by acblackford** [NASA-IMPACT/veda-data#24]
### Contact Details

acb0068@uah.edu

### Data Location

https://drive.google.com/drive/folders/18BAU77GH-TlAx1UOrszmYCO-bIVkxFP9?usp=drive_link

### Size Estimate

700 MB

### Number of Items

4

### Description

MODIS difference cogs of LST Day , LST Night, NDVI, and WSA Albedo over the Camp Fire domain. Data should be centered on 0, (i.e., -1 to 1). 

### Checklist

- [X] Files are valid COGs. Use [`rio cogeo validate`](https://cogeotiff.github.io/rio-cogeo/Is_it_a_COG/#3-cog-validation)
- [X] COGs appear to be correct

### To Do

- [x] Open PR for publishing those datasets to the Staging API
- [x] Notify QA / move ticket to QA state
- [ ] Once approved, merge and close

**Comment by kathrynberger** [comment]
Repeatedly receiving 422 Client Errors while trying to ingest this new dataset. I'm starting with the NDVI differences dataset first with the following code (see [Gist](https://gist.github.com/kathrynberger/a338cea7979cf8013f92038d2ab4fdd1)). 

I suspect that it has to do with the date formatting, but the error messages are unclear as to the root issue. I don't see any obvious errors, but would appreciate a second set of eyes on this @slesaad @ividito Thanks!

**Comment by kathrynberger** [comment]
Update on above errorrs: 
Currently seeking guidance on how to format target file name for files comparing two different time steps (e.g.,  `CampFire_NDVI_2015_2022_diff_cog.tif`). [Documentation](https://nasa-impact.github.io/veda-docs/contributing/dataset-ingestion/file-preparation.html) only provides guidance for single time step or time range. cc' @slesaad @ividito

**Comment by kathrynberger** [comment]
Checklist for datasets added to staging from this ticket

- [ ] CampFire NDVI difference 2015-2022
- [ ] CampFire Albedo WSA difference 2015-2022
- [ ] Campfire LST Day 2015-2022
- [ ] Campfire LST Night 2015-2022

**Comment by kathrynberger** [comment]
All of these datasets are now available in the stac catalog: 
https://staging-stac.delta-backend.com/collections/modis-ndvi-diff-2015-2022
https://staging-stac.delta-backend.com/collections/modis-lst-night-diff-2015-2022
https://staging-stac.delta-backend.com/collections/modis-lst-day-diff-2015-2022
https://staging-stac.delta-backend.com/collections/modis-albedo-wsa-diff-2015-2022

**Comment by j08lue** [comment]
- https://github.com/NASA-IMPACT/veda-data/pull/34
- https://github.com/NASA-IMPACT/veda-data/pull/35
- https://github.com/NASA-IMPACT/veda-data/pull/36
- https://github.com/NASA-IMPACT/veda-data/pull/37
