### ISSUE TITLE
New Dataset: Maui Fire

### ISSUE THREAD

**Issue by acblackford** [NASA-IMPACT/veda-data#28]
### Contact Details

acb0068@uah.edu

### URL/DOI

https://search.earthdata.nasa.gov/search/

### Data Location

https://drive.google.com/drive/folders/11w1icaMv7UGqd-hYWsn4_23ZVP-9hU8_?usp=drive_link

### Size Estimate

200 MB

### Number of Items

4

### Description

HLS data from before and after the Lahaina Fire. The two falsecolor imagery cogs are one dataset, and the other two belong to a seprate ID.

### Checklist

- [X] Files are valid COGs. Use [`rio cogeo validate`](https://cogeotiff.github.io/rio-cogeo/Is_it_a_COG/#3-cog-validation)
- [X] COGs appear to be correct

### To Do

- [ ] Open PR for publishing those datasets to the Staging API
- [ ] Notify QA / move ticket to QA state
- [ ] Once approved, merge and close

**Comment by kathrynberger** [comment]
@acblackford it appears that the link provided in the `Data Drive` is no longer valid (it appears the contents have been moved), can you verify and send a new link?

**Comment by acblackford** [comment]
@kathrynberger I apologize- try this like: https://drive.google.com/drive/folders/1_y-imMXzjxSiZfOSLf-v-MvXne-v-pGl?usp=sharing

**Comment by kathrynberger** [comment]
Just tried to request access to the the drive

**Comment by slesaad** [comment]
All these datasets are now available in the stac catalog. 
https://staging-stac.delta-backend.com/collections/landsat-nighttime-thermal
https://staging-stac.delta-backend.com/collections/hls-swir-falsecolor-composite
https://staging-stac.delta-backend.com/collections/hls-bais2
