### ISSUE TITLE
Urban Heating Dataset Overview dataset poorly configured

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data#30]
The Urban Heating dataset is poorly configured. The title is "Urban Heating Dataset Overview", which is probably not correct, and the dataset page is Lorem Ipsum: https://www.earthdata.nasa.gov/dashboard/data-catalog/urban-heating

![image](https://github.com/NASA-IMPACT/veda-data/assets/3404817/36144a27-1db5-4265-9fb2-9fdec4ef29b3)

Kindly pointed out by @kathrynberger.

## Acceptance criteria

- [x] Either fixed the title & description or unpublished the dataset

**Comment by moradology** [comment]
I was going to remove this page but ended up getting some support form a UAH student. I anticipate that he will lodge a PR to fix the issue but will pick things up after he's written a suitable description if he's not comfortable with that

**Comment by moradology** [comment]
https://github.com/NASA-IMPACT/veda-config/pull/308

**Comment by j08lue** [comment]
Fixed in
- https://github.com/NASA-IMPACT/veda-config/pull/308
