### ISSUE TITLE
Transfer collection-level provider information into STAC

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data#39]
We completed the collection of provider information for the VEDA STAC collections. For some, we were unable to gather the information, but this is as good as it gets.

- https://github.com/NASA-IMPACT/veda-data/issues/22

Now we should transfer this information to our VEDA STAC collections (in staging) - hopefully this is scriptable.

We should also note in the spreadsheet, which datasets we were not able to get the information for.

## Acceptance criteria

- [ ] Transferred provider information from [data collection spreadsheet](https://docs.google.com/spreadsheets/d/1hF74CLrVktNVKfNg9W14uNXcgT2OvzX5q1GEgtru9Ig) into STAC, where available
- [ ] Mark the collections where information is still incomplete

**Comment by smohiudd** [comment]
This is related to https://github.com/NASA-IMPACT/veda-architecture/issues/311 which will involve recreating the dataset configs file in a new format that works with the stac ingestor in preparation for ingestion into Production. We can also add the Provider metadata at that time.

**Comment by anayeaye** [comment]
addressed in https://github.com/NASA-IMPACT/veda-architecture/issues/311
