### ISSUE TITLE
New Dataset: CYGNSS Surface Water Inundation Fractiion, UCAR/CU

### ISSUE THREAD

**Issue by freitagb** [NASA-IMPACT/veda-data#40]
### Contact Details

brian.m.freitag@nasa.gov

### Data License Identifier

CC-BY-NC-SA-1.0

### Data Location

s3://veda-data-store-staging/cygnss-watermask-ucar/

### Size Estimate

4 GB

### Number of Items

1929

### Description

The UCAR/CU team led by investigator Clara Chew (clara@muonspace.com) has developed a surface water inundation fraction product using CYGNSS observations.

### Checklist

- [ ] Files are valid COGs. Use [`rio cogeo validate`](https://cogeotiff.github.io/rio-cogeo/Is_it_a_COG/#3-cog-validation)
- [ ] COGs appear to be correct

### To Do

- [ ] Open PR for publishing those datasets to the Staging API
- [ ] Notify QA / move ticket to QA state
- [ ] Once approved, merge and close

**Comment by freitagb** [comment]
Collection json 

> {
>     "id": "cygnss_watermask_ucar",
>     "type": "Collection",
>     "links": [
>         {
>             "rel": "items",
>             "type": "application/geo+json",
>             "href": "https://staging-stac.delta-backend.com/collections/cygnss_watermask_ucar/items"
>         },
>         {
>             "rel": "parent",
>             "type": "application/json",
>             "href": "https://staging-stac.delta-backend.com/"
>         },
>         {
>             "rel": "root",
>             "type": "application/json",
>             "href": "https://staging-stac.delta-backend.com/"
>         },
>         {
>             "rel": "self",
>             "type": "application/json",
>             "href": "https://staging-stac.delta-backend.com/collections/cygnss_watermask_ucar"
>         }
>     ],
>     "title": "CYGNSS Surface Water Inundation Fractiion, UCAR/CU",
>     "assets": null,
>     "is_periodic": true,
>     "time_density": "day",
>     "extent": {
>         "spatial": {
>             "bbox": [
>                 [
>                     -180,
>                     -40.01145939,
>                     180,
>                     40.01145939
>                 ]
>             ]
>         },
>         "temporal": {
>             "interval": [
>                 [
>                     "2017-03-20 00:00:00+00",
>                     "2022-06-30 00:00:00+00"
>                 ]
>             ]
>         }
>     },
>     "license": "CC-BY-NC-SA-1.0",
>     "keywords": null,
>     "providers": null,
>     "summaries": {
>         "datetime": [
>             "2017-03-20T00:00:00Z"
>         ]
>     },
>     "description": "The UCAR/CU team led by investigator Clara Chew (clara@muonspace.com) has developed a surface water inundation fraction product using CYGNSS observations. Reference: Clara Chew, Eric Small, Hannah Huelsing, Flooding and inundation maps using interpolated CYGNSS reflectivity observations, Remote Sensing of Environment, Volume 293, 2023, 113598, ISSN 0034-4257, https://doi.org/10.1016/j.rse.2023.113598.",
>     "item_assets": {
>         "cog_default": {
>             "type": "image/tiff; application=geotiff; profile=cloud-optimized",
>             "roles": [
>                 "data",
>                 "layer"
>             ],
>             "title": "Default COG Layer",
>             "description": "Cloud optimized default layer to display on map"
>         }
>     },
>     "stac_version": "1.0.0",
>     "stac_extensions": null,
>     "dashboard:is_periodic": true,
>     "dashboard:time_density": "day"
> }

**Comment by slesaad** [comment]
https://github.com/NASA-IMPACT/veda-data/pull/51
