### ISSUE TITLE
New Dataset: CYGNSS Surface Watermask (with lakes), UC Berkeley

### ISSUE THREAD

**Issue by freitagb** [NASA-IMPACT/veda-data#41]
### Contact Details

brian.m.freitag@nasa.gov

### Data License Identifier

CC-BY-NC-SA-1.0

### Data Location

s3://veda-data-store-staging/cygnss-watermask-ucberkeley/

### Size Estimate

219 MB

### Number of Items

57

### Description

The UC Berkeley team led by investigator Cynthia Gerlein-Safdi has developed a novel surface watermask product using CYGNSS observations.

### Checklist

- [ ] Files are valid COGs. Use [`rio cogeo validate`](https://cogeotiff.github.io/rio-cogeo/Is_it_a_COG/#3-cog-validation)
- [ ] COGs appear to be correct

### To Do

- [ ] Open PR for publishing those datasets to the Staging API
- [ ] Notify QA / move ticket to QA state
- [ ] Once approved, merge and close

**Comment by freitagb** [comment]
Collection json

> {
>     "id": "cygnss-watermask-ucberkeley",
>     "type": "Collection",
>     "links": [
>         {
>             "rel": "items",
>             "type": "application/geo+json",
>             "href": "https://staging-stac.delta-backend.com/collections/cygnss-watermask-ucberkeley/items"
>         },
>         {
>             "rel": "parent",
>             "type": "application/json",
>             "href": "https://staging-stac.delta-backend.com/"
>         },
>         {
>             "rel": "root",
>             "type": "application/json",
>             "href": "https://staging-stac.delta-backend.com/"
>         },
>         {
>             "rel": "self",
>             "type": "application/json",
>             "href": "https://staging-stac.delta-backend.com/collections/cygnss-watermask-ucberkeley"
>         }
>     ],
>     "title": "CYGNSS Surface Watermask (with lakes), UC Berkeley",
>     "assets": null,
>     "is_periodic": true,
>     "time_density": "month",
>     "extent": {
>         "spatial": {
>             "bbox": [
>                 [
>                     -180,
>                     -37.4050000,
>                     180,
>                     37.4050000
>                 ]
>             ]
>         },
>         "temporal": {
>             "interval": [
>                 [
>                     "2018-08-01 00:00:00+00",
>                     "2023-04-01 00:00:00+00"
>                 ]
>             ]
>         }
>     },
>     "license": "CC-BY-NC-SA-1.0",
>     "keywords": null,
>     "providers": null,
>     "summaries": {
>         "datetime": [
>             "2018-08-01T00:00:00Z"
>         ]
>     },
>     "description": "The UC Berkeley team led by investigator Cynthia Gerlein-Safdi has developed a novel surface watermask product using CYGNSS observations. Information at the pixel-level is combined with topographic and othe information in a computer vision based algorithm to segment land and surface water classes.",
>     "item_assets": {
>         "cog_default": {
>             "type": "image/tiff; application=geotiff; profile=cloud-optimized",
>             "roles": [
>                 "data",
>                 "layer"
>             ],
>             "title": "Default COG Layer",
>             "description": "Cloud optimized default layer to display on map"
>         }
>     },
>     "stac_version": "1.0.0",
>     "stac_extensions": null,
>     "dashboard:is_periodic": true,
>     "dashboard:time_density": "month"
> }

**Comment by slesaad** [comment]
https://github.com/NASA-IMPACT/veda-data/pull/51
