### ISSUE TITLE
STAC objects should not have `stac_extensions` set to null

### ISSUE THREAD

**Issue by jsignell** [NASA-IMPACT/veda-data#55]
According to the [spec](https://github.com/radiantearth/stac-spec/blob/v1.0.0/collection-spec/json-schema/collection.json) `stac_extensions` can not exist in the json blob or it can be an empty list, but it cannot be null.

The following collections have `"stac_extensions": null"`:

```
sport-lis-vsm0_100cm-percentile
lis-global-da-gws
eis_fire_fireline
lis-global-da-evap
eis_fire_newfirepix
eis_fire_perimeter
lis-global-da-gpp
lis-global-da-swe
lis-global-da-qs
lis-tvegsuppression
CMIP245-winter-median-pr
CMIP245-winter-median-ta
CMIP585-winter-median-pr
barc-thomasfire
conus-reach
disalexi-etsuppression
CMIP585-winter-median-ta
frp-max-thomasfire
houston-lst-diff
lis-global-da-tws
lis-global-da-tws-trend
houston-landcover
houston-aod
lis-global-da-gpp-trend
lis-global-da-qsb
lis-global-da-streamflow
lis-etsuppression
lis-global-da-totalprecip
```

NOTE: This doesn't cause the collections to fail when running `collection.validate()` because as part of that process a collection is created from a dict and then a dict is dumped back out and in that process any `"stac_extensions": null` are dropped.

**Comment by anayeaye** [comment]
this should be corrected when the updated collections in veda-data are published (tracked in https://github.com/NASA-IMPACT/veda-architecture/issues/311)
