### ISSUE TITLE
Add COVID Chlorophyll-a Anomaly Dataset

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-data#60]
Dataset is stored in: `s3://covid-eo-data/oc3_chla_anomaly/`

- [x] Verify that files are valid COGs (e.g. with [`rio cogeo validate`](https://cogeotiff.github.io/rio-cogeo/Is_it_a_COG/#3-cog-validation))
- [x] Gather STAC collection metadata

  - id: oc3-chla-anomaly-covid-19
  - title: Chlorophyll-a Anomaly
  - description: Chlorophyll is an indicator of algae growth. Redder colors indicate increases in chlorophyll-a and worse water quality. Bluer colors indicate decreases in chlorophyll-a and improved water quality. White areas indicate no change.
  - license: CC0-1.0
  - temporal interval: 2018 to 2021
  - dashboard is periodic: True  (note that these are spotlight areas so the date range may vary at different locations, this is similar to nighlights hd monthly already in the VEDA catalog)
  - the dashboard time density: month

## Notes
- This collection appears in the Water Quality and Covid 19 story
- [Covid-19 dashboard migration wrap up doc](https://docs.google.com/document/d/1xiBf9Awo8DShrRJhMZcfhunchEynUTA52xHzYZQZ0HE/edit#)
- veda-config [Covid 19 Water Quality discovery issue](https://github.com/NASA-IMPACT/veda-config/pull/231)

- [ ] Review and follow https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/OPERATING.md

## AC
- [ ] Migrate oc3_chla_anomaly data to veda-data-store-staging and ingest
- [ ] Once approved, merge and close.
- [ ] Notify @danielfdsilva and @nerik that this Covid 19 Water Quality chlorophyll collection has been migrated

**Comment by anayeaye** [comment]
closing, no current requests open for this covid-19 demo dataset
