### ISSUE TITLE
The Forest Fire layer (dailies) has spots with some interpolation towards the center

### ISSUE THREAD

**Issue by Catalina-Moller** [NASA-IMPACT/veda-data#68]
### Description:
In the Dataset EPA - Other in the layer Forest Fires (daily) you can see the layer with several spots with some kind of interpolation towards the center. 
 
**Evidence:** [Video ](https://www.screencast.com/t/mmbsxIUJ)

![image](https://user-images.githubusercontent.com/111894012/201740947-a9e6bf49-dad6-4357-ba77-b4b11b549b26.png)

https://www.earthdata.nasa.gov/dashboard/eis/datasets/epa-other/explore?datetime=2012-01-01T00%3A00%3A00.000Z&layer=epa-daily-emissions_5_forest_fires&position=-96.0397%7C36.1956%7C8.93

**Comment by j08lue** [comment]
No one has complained about this for a while, so I guess it is fine or does not matter.
