### ISSUE TITLE
Convert and publish GPM IMERG dataset to COG

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data#73]
## Epic

None, but to support the ArcGIS Enterprise in the Cloud Effort

## Description

Convert the half-hour product to COG for use by ADC initiative
* Product description and data access: https://disc.gsfc.nasa.gov/datasets/GPM_3IMERGHHE_06/summary,
* daily, half-hourly and monthly are all listed in the ADC dataset spreadsheet, variable PreciptationCal  and Preciptation respectively https://docs.google.com/spreadsheets/d/1XS4VS8_MKsbeH8ncHcN_LClURodO1tg-/edit#gid=958058316
* but Brian Tisdale mentioned the half-hourly specifically over slack, so proposing we start there
* In order to make this a useful / reusable workflow, @ingalls proposed making an API and simple UI for generating COGs. This use case will serve as the first use case to prototype that idea. However that API and UI being end-user ready is not a requirement for this task.

### Background

Brian Tisdale who is leading the ArcGIS Enterprise in the Cloud effort reached out on slack:

>The newly formed ArcGIS Enterprise in the Cloud team is starting to get their footing and ready to dive into the details of how the GIS component of VEDA will be integrated. I know we have the larger stakeholder sync next week but hoping we can coordinate on a few questions prior. As GPM is a priority dataset for both VEDA and ArcGIS Enterprise, we'd like to propose focusing on it for initial prototyping to inform the cross-team decisions that will need to be made. Provided below is a link to our GPM ArcGIS Image Service API. It's currently hosted at Goddard but will be migrated to the Earthdata Cloud as part of the ArcGIS Enterprise in the Cloud activity. Most of our initial questions are based on how the COG generation is going to occur. Do you know if VEDA or EIS has started COG generation for GPM?
> GPM ArcGIS Image Service API: https://arcgis.gesdisc.eosdis.nasa.gov/authoritative/rest/services/GPM_3IMERGHHE_06/ImageServer

I sent Brian an email message:
If I understand correctly, to support the ADC (or is it a different acronym now "ArcGIS Enterprise in the Cloud"?) we want to:
1. Ingest and publish [GPM 3IMERG HHE 06](https://disc.gsfc.nasa.gov/datasets/GPM_3IMERGHHE_06/summary) data into the VEDA metadata API (STAC)
2. We want to create Cloud-Optimized GeoTIFFs to support services described below
3. Publish services for visualization: I see there is a WMS service - would WMTS be ok to support ArGIS in the Cloud or it must be WMS?
4. Publish services for access: We will need WCS support for ArcGIS Enterprise in the Cloud

GPM IMERG is a high value first example of executing the above steps but there will be many other datasets to follow a similar model to the above.

### Acceptance Criteria:

- [ ] GPM IMERG in COG shared with Brian Tisdale for inspection
- [ ] Publish a few files to dev STAC API and share API for dynamic visualization and testing in ArcGIS Enterprise interface
- [ ] Document some lessens and best practices for COG conversion and publishing to support clients like ArcGIS. What did we learn about the conversion scripts required and challenges that should inform the final API design, UI design, and implementation?
- [ ] Demo any API and UI developed in this effort

**Comment by j08lue** [comment]
Stale
