### ISSUE TITLE
Automate production of facebook population data layer and STAC generation

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data#78]
## Description
Many datasets will be accumulating data in an ongoing basis. This ticket is intended to automated the production of facebook population data, and should serve as a reference implementation so that other datasets can be automated easily in the future.

## Acceptance Criteria
- [ ] New facebook data is automatically updated in VEDA datastore on a monthly basis (this frequency should be easily adjustable for future datasets that might be updated more/less frequently, see https://github.com/NASA-IMPACT/veda-architecture/issues/26)

### Checklist under previous ticket (old)
For each dataset, we will follow the following steps:
1. - [x] Identify dataset and where it will be accessed from. 
    `s3://covid-eo-data/dataforgood-fb-population-density/hrsl_general_latest_global_cog.tif`, the current dataset has this configuration file https://github.com/NASA-IMPACT/covid-api/blob/develop/covid_api/db/static/datasets/fb-population-density.json
2. - [x] If the dataset is ongoing (i.e. new files are continuously added and should be included in the dashboard), design and construct the forward-processing workflow. 
   I don't believe this dataset is ongoing at this time
3. - [x] Verify the COG output with the science team by sharing in a visual interface.
4. - [x] Verify the metadata output with STAC API developers and any systems which may be depending on this STAC metadata (e.g. the front-end dev team).
7. - [x] Add the dataset to the ~production dashboard~ staging API

**Comment by j08lue** [comment]
Stale
